-- Generated by jit_update — do not edit by hand
JustInTimeData = {
  meta = {
    generated_at = "2026-04-25T02:08:08Z",
    schema_version = 1,
    season = "season-mn-1",
  },
  affix_id_to_slug = {
    [9] = "tyrannical",
    [10] = "fortified",
    [147] = "xalataths-guile",
  },
  dungeons = {
    ["algethar-academy"] = {
      bosses = {
        {
          name = "Vexamus",
          ordinal = 0,
          slug = "vexamus",
          wow_encounter_id = 2562,
        },
        {
          name = "Overgrown Ancient",
          ordinal = 1,
          slug = "overgrown-ancient",
          wow_encounter_id = 2563,
        },
        {
          name = "Crawth",
          ordinal = 2,
          slug = "crawth",
          wow_encounter_id = 2564,
        },
        {
          name = "Echo of Doragosa",
          ordinal = 3,
          slug = "echo-of-doragosa",
          wow_encounter_id = 2565,
        },
      },
      challenge_mode_id = 402,
      levels = {
        [18] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 1124771, 300219, 754649, 1556485 },
            clear_time_ms = 1586528,
            sample_size = 2,
          },
        },
        [19] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 1224167, 296806, 741817, 1649062 },
            clear_time_ms = 1651782,
            sample_size = 3,
          },
        },
        [20] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 1224414, 321352, 801408, 1694880 },
            clear_time_ms = 1726108,
            sample_size = 3,
          },
        },
      },
      num_bosses = 4,
      short_name = "AA",
      timer_ms = 1800000,
    },
    ["magisters-terrace"] = {
      bosses = {
        {
          name = "Arcanotron Custos",
          ordinal = 0,
          slug = "arcanotron-custos",
          wow_encounter_id = 3071,
        },
        {
          name = "Seranel Sunlash",
          ordinal = 1,
          slug = "seranel-sunlash",
          wow_encounter_id = 3072,
        },
        {
          name = "Gemellus",
          ordinal = 2,
          slug = "gemellus",
          wow_encounter_id = 3073,
        },
        {
          name = "Degentrius",
          ordinal = 3,
          slug = "degentrius",
          wow_encounter_id = 3074,
        },
      },
      challenge_mode_id = 558,
      levels = {
        [19] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 431511, 834981, 1263131, 1648761 },
            clear_time_ms = 1719942,
            sample_size = 3,
          },
        },
        [20] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 480508, 879874, 1374645, 1765136 },
            clear_time_ms = 1795798,
            sample_size = 3,
          },
        },
      },
      num_bosses = 4,
      short_name = "MT",
      timer_ms = 2040000,
    },
    ["maisara-caverns"] = {
      bosses = {
        {
          name = "Muro'jin and Nekraxx",
          ordinal = 0,
          slug = "murojin-and-nekraxx",
          wow_encounter_id = 3212,
        },
        {
          name = "Vordaza",
          ordinal = 1,
          slug = "vordaza",
          wow_encounter_id = 3213,
        },
        {
          name = "Rak'tul, Vessel of Souls",
          ordinal = 2,
          slug = "raktul-vessel-of-souls",
          wow_encounter_id = 3214,
        },
      },
      challenge_mode_id = 560,
      levels = {
        [19] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 677532, 1537983, 1847902, 1759312 },
            clear_time_ms = 1670723,
            sample_size = 2,
          },
        },
        [20] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 647026, 1372802, 1737971, 1758279 },
            clear_time_ms = 1778587,
            sample_size = 3,
          },
        },
      },
      num_bosses = 3,
      short_name = "MC",
      timer_ms = 1980000,
    },
    ["nexuspoint-xenas"] = {
      bosses = {
        {
          name = "Chief Corewright Kasreth",
          ordinal = 0,
          slug = "chief-corewright-kasreth",
          wow_encounter_id = 3328,
        },
        {
          name = "Corewarden Nysarra",
          ordinal = 1,
          slug = "corewarden-nysarra",
          wow_encounter_id = 3332,
        },
        {
          name = "Lothraxion",
          ordinal = 2,
          slug = "lothraxion",
          wow_encounter_id = 3333,
        },
      },
      challenge_mode_id = 559,
      levels = {
        [19] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 435735, 1008831, 1512217, 1520096 },
            clear_time_ms = 1527975,
            sample_size = 2,
          },
        },
        [20] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 452506, 1099793, 1584344, 1609639 },
            clear_time_ms = 1634934,
            sample_size = 2,
          },
        },
      },
      num_bosses = 3,
      short_name = "NPX",
      timer_ms = 1800000,
    },
    ["pit-of-saron"] = {
      bosses = {
        {
          name = "Forgemaster Garfrost",
          ordinal = 0,
          slug = "forgemaster-garfrost",
          wow_encounter_id = 1999,
        },
        {
          name = "Ick and Krick",
          ordinal = 1,
          slug = "ick-and-krick",
          wow_encounter_id = 2001,
        },
        {
          name = "Scourgelord Tyrannus",
          ordinal = 2,
          slug = "scourgelord-tyrannus",
          wow_encounter_id = 2000,
        },
      },
      challenge_mode_id = 556,
      levels = {
        [19] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 693083, 1054532, 1533519, 1533793 },
            clear_time_ms = 1534068,
            sample_size = 3,
          },
        },
        [20] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 781727, 1155916, 1621893, 1622613 },
            clear_time_ms = 1623333,
            sample_size = 3,
          },
        },
      },
      num_bosses = 3,
      short_name = "POS",
      timer_ms = 1800000,
    },
    ["seat-of-the-triumvirate"] = {
      bosses = {
        {
          name = "Zuraal the Ascended",
          ordinal = 0,
          slug = "zuraal-the-ascended",
          wow_encounter_id = 2065,
        },
        {
          name = "Saprish",
          ordinal = 1,
          slug = "saprish",
          wow_encounter_id = 2066,
        },
        {
          name = "Viceroy Nezhar",
          ordinal = 2,
          slug = "viceroy-nezhar",
          wow_encounter_id = 2067,
        },
        {
          name = "L'ura",
          ordinal = 3,
          slug = "lura",
          wow_encounter_id = 2068,
        },
      },
      challenge_mode_id = 239,
      levels = {
        [19] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 881268, 1321902, 1542219, 1652378 },
            clear_time_ms = 1762537,
            sample_size = 2,
          },
        },
        [20] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 325720, 1102378, 1528830, 1845006 },
            clear_time_ms = 1890960,
            sample_size = 3,
          },
        },
      },
      num_bosses = 4,
      short_name = "SEAT",
      timer_ms = 2040000,
    },
    skyreach = {
      bosses = {
        {
          name = "Ranjit",
          ordinal = 0,
          slug = "ranjit",
          wow_encounter_id = 1698,
        },
        {
          name = "Araknath",
          ordinal = 1,
          slug = "araknath",
          wow_encounter_id = 1699,
        },
        {
          name = "Rukhran",
          ordinal = 2,
          slug = "rukhran",
          wow_encounter_id = 1700,
        },
        {
          name = "High Sage Viryx",
          ordinal = 3,
          slug = "high-sage-viryx",
          wow_encounter_id = 1701,
        },
      },
      challenge_mode_id = 161,
      levels = {
        [19] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 278601, 713862, 901440, 1340852 },
            clear_time_ms = 1431620,
            sample_size = 2,
          },
        },
        [20] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 399071, 767788, 1011170, 1505318 },
            clear_time_ms = 1541215,
            sample_size = 3,
          },
        },
      },
      num_bosses = 4,
      short_name = "SR",
      timer_ms = 1680000,
    },
    ["windrunner-spire"] = {
      bosses = {
        {
          name = "Emberdawn",
          ordinal = 0,
          slug = "emberdawn",
          wow_encounter_id = 3056,
        },
        {
          name = "Derelict Duo",
          ordinal = 1,
          slug = "derelict-duo",
          wow_encounter_id = 3057,
        },
        {
          name = "Commander Kroluk",
          ordinal = 2,
          slug = "commander-kroluk",
          wow_encounter_id = 3058,
        },
        {
          name = "Restless Heart",
          ordinal = 3,
          slug = "restless-heart",
          wow_encounter_id = 3059,
        },
      },
      challenge_mode_id = 557,
      levels = {
        [19] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 553928, 1032612, 1495028, 1732141 },
            clear_time_ms = 1748911,
            sample_size = 3,
          },
        },
        [20] = {
          ["fortified-tyrannical-xalataths-guile"] = {
            boss_splits_ms = { 581016, 1058999, 1568659, 1807762 },
            clear_time_ms = 1831049,
            sample_size = 2,
          },
        },
      },
      num_bosses = 4,
      short_name = "WS",
      timer_ms = 1980000,
    },
  },
}
