"""Render a pipeline document dict to Data.lua text (schema v2)."""

from __future__ import annotations

from typing import Any


def render_data_lua(doc: dict[str, Any]) -> str:
    """Render a document dict to a Data.lua text body (schema v2).

    Schema v2 changes vs v1:
      * No ``affix_id_to_slug`` table at top level
      * ``dungeons[d].levels[L]`` is a direct dict (no per-affix sub-key)
      * Each cell carries a ``splits_source`` field
      * ``meta.schema_version = 2`` and ``meta.source = "blizzard+raiderio"``

    Output is deterministic (sorted keys at every level) so day-to-day diffs
    stay readable.

    Args:
        doc: The pipeline document dict with keys ``meta`` and ``dungeons``.

    Returns:
        A Lua source string declaring the ``JustInTimeData`` global table.
    """
    lines: list[str] = []
    lines.append("-- Auto-generated by scripts/jit_update. Do not edit by hand.")
    lines.append("JustInTimeData = {")

    meta = doc.get("meta", {})
    lines.append("  meta = {")
    lines.append(f'    generated_at   = "{meta.get("generated_at", "")}",')
    lines.append(f"    schema_version = {int(meta.get('schema_version', 2))},")
    lines.append(f'    season         = "{meta.get("season", "")}",')
    lines.append(f'    source         = "{meta.get("source", "blizzard+raiderio")}",')
    lines.append("  },")
    lines.append("")
    lines.append("  dungeons = {")

    for slug in sorted(doc.get("dungeons", {}).keys()):
        dungeon = doc["dungeons"][slug]
        lines.append(f'    ["{slug}"] = {{')
        lines.append(f"      keystone_timer_ms = {int(dungeon.get('keystone_timer_ms', 0))},")
        # Bosses sub-table
        lines.append("      bosses = {")
        for ord_key in sorted(dungeon.get("bosses", {}).keys()):
            b = dungeon["bosses"][ord_key]
            lines.append(
                f'        [{int(ord_key)}] = {{ ordinal = {int(b.get("ordinal", ord_key))}, '
                f'slug = "{b.get("slug", "")}", name = "{_escape_lua_string(b.get("name", ""))}" }},'
            )
        lines.append("      },")
        # Levels sub-table — direct, no affix nesting
        lines.append("      levels = {")
        for level in sorted(dungeon.get("levels", {}).keys()):
            cell = dungeon["levels"][level]
            splits_lua = "{" + ", ".join(str(int(v)) for v in cell.get("boss_splits_ms", [])) + "}"
            lines.append(f"        [{int(level)}] = {{")
            lines.append(f"          clear_time_ms  = {int(cell.get('clear_time_ms', 0))},")
            lines.append(f"          boss_splits_ms = {splits_lua},")
            lines.append(f"          sample_size    = {int(cell.get('sample_size', 0))},")
            lines.append(f'          splits_source  = "{cell.get("splits_source", "")}",')
            lines.append("        },")
        lines.append("      },")
        lines.append("    },")

    lines.append("  },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _escape_lua_string(s: str) -> str:
    """Escape characters that would break a Lua double-quoted string.

    Apostrophes are safe inside double-quoted Lua strings and are left as-is.
    Only backslash and double-quote require escaping.

    Args:
        s: The raw Python string.

    Returns:
        The escaped string suitable for use inside Lua double quotes.
    """
    return s.replace("\\", "\\\\").replace('"', '\\"')
