"""Render a Python document into a deterministic Lua declaration string."""

from __future__ import annotations

from typing import Any

INDENT = "  "
HEADER = "-- Generated by jit_update — do not edit by hand\n"


def render_data_lua(document: dict[str, Any]) -> str:
    """Render the full Data.lua content for a JustInTime document.

    Output is byte-deterministic given the same input (sorted keys, fixed indent).
    Top-level shape::

        {
          "meta": {...},
          "affix_id_to_slug": {<int>: <str>, ...},
          "dungeons": {<slug>: <dungeon dict>, ...},
        }

    Args:
        document: The document dict with keys ``meta``, ``affix_id_to_slug``,
            and ``dungeons``.

    Returns:
        A Lua source string declaring the ``JustInTimeData`` global table.
    """
    parts: list[str] = [HEADER, "JustInTimeData = {\n"]
    parts.append(_render_kv(1, "meta", document.get("meta", {})))
    parts.append(_render_kv(1, "affix_id_to_slug", document.get("affix_id_to_slug", {})))
    parts.append(_render_kv(1, "dungeons", document.get("dungeons", {})))
    parts.append("}\n")
    return "".join(parts)


def _render_kv(level: int, key: str, value: Any) -> str:
    """Render a single key-value pair at the given indent level.

    Args:
        level: Indentation level (number of INDENT units).
        key: The Lua key name (must be a valid Lua identifier).
        value: The Python value to render.

    Returns:
        A formatted ``key = value,\\n`` string.
    """
    indent = INDENT * level
    return f"{indent}{key} = {_render_value(level, value)},\n"


def _render_value(level: int, value: Any) -> str:
    """Render a Python value as a Lua literal.

    Args:
        level: Current indentation level (used for nested structures).
        value: The Python value to render.

    Returns:
        A Lua literal string.

    Raises:
        TypeError: If ``value`` is of an unsupported type.
    """
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    if isinstance(value, str):
        return _quote(value)
    if value is None:
        return "nil"
    if isinstance(value, list):
        return _render_list(level, value)
    if isinstance(value, dict):
        return _render_dict(level, value)
    raise TypeError(f"unsupported value type: {type(value).__name__}")


def _render_list(level: int, items: list[Any]) -> str:
    """Render a Python list as a Lua array table.

    Integer-only lists are rendered as compact one-liners. Mixed/nested lists
    are rendered multi-line.

    Args:
        level: Current indentation level.
        items: The list to render.

    Returns:
        A Lua table constructor string.
    """
    if not items:
        return "{}"
    if all(isinstance(x, int) for x in items):
        # boss_splits_ms style — compact one-liner
        inner = ", ".join(str(x) for x in items)
        return "{ " + inner + " }"
    indent = INDENT * (level + 1)
    closing = INDENT * level
    lines = ["{\n"]
    for item in items:
        lines.append(f"{indent}{_render_value(level + 1, item)},\n")
    lines.append(f"{closing}}}")
    return "".join(lines)


def _render_dict(level: int, items: dict[Any, Any]) -> str:
    """Render a Python dict as a Lua hash table.

    Keys are sorted deterministically: integers numerically first, then strings
    alphabetically.

    Args:
        level: Current indentation level.
        items: The dict to render.

    Returns:
        A Lua table constructor string.
    """
    if not items:
        return "{}"
    indent = INDENT * (level + 1)
    closing = INDENT * level
    lines = ["{\n"]
    for k, v in _sorted_items(items):
        rendered_key = _render_dict_key(k)
        lines.append(f"{indent}{rendered_key} = {_render_value(level + 1, v)},\n")
    lines.append(f"{closing}}}")
    return "".join(lines)


def _sorted_items(items: dict[Any, Any]) -> list[tuple[Any, Any]]:
    """Sort dict items deterministically: ints by numeric value, strs alphabetically.

    Integer keys sort before string keys.

    Args:
        items: The dict whose items to sort.

    Returns:
        A sorted list of ``(key, value)`` pairs.
    """
    return sorted(
        items.items(),
        key=lambda kv: (0, kv[0]) if isinstance(kv[0], int) else (1, kv[0]),
    )


def _render_dict_key(k: Any) -> str:
    """Render a dict key as a Lua table key expression.

    Args:
        k: The Python key (int or str).

    Returns:
        A Lua key string, e.g. ``[42]`` or ``slug`` or ``["hyphen-key"]``.

    Raises:
        TypeError: If ``k`` is not an int or str.
    """
    if isinstance(k, int):
        return f"[{k}]"
    if isinstance(k, str):
        if _is_lua_identifier(k):
            return k
        return f"[{_quote(k)}]"
    raise TypeError(f"unsupported dict key type: {type(k).__name__}")


def _is_lua_identifier(s: str) -> bool:
    """Return True if *s* is a valid bare Lua identifier.

    Args:
        s: The string to test.

    Returns:
        ``True`` if *s* can be used as a bare Lua table key.
    """
    if not s:
        return False
    if not (s[0].isalpha() or s[0] == "_"):
        return False
    return all(c.isalnum() or c == "_" for c in s)


def _quote(s: str) -> str:
    """Return *s* as a double-quoted Lua string literal.

    Args:
        s: The raw Python string.

    Returns:
        A Lua-escaped double-quoted string, e.g. ``"hello \\"world\\""``
    """
    escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'
