-- Generated by jit_update — do not edit by hand
JustInTimeData = {
  meta = {
    generated_at = "2026-04-25T14:30:00Z",
    schema_version = 1,
    season = "season-mn-1",
  },
  affix_id_to_slug = {
    [9] = "tyrannical",
    [10] = "fortified",
    [147] = "xalataths-guile",
  },
  dungeons = {
    ["algethar-academy"] = {
      bosses = {
        {
          name = "Overgrown Ancient",
          ordinal = 1,
          slug = "overgrown-ancient",
          wow_encounter_id = 2563,
        },
        {
          name = "Boss 2",
          ordinal = 2,
          slug = "boss2",
          wow_encounter_id = 2564,
        },
        {
          name = "Boss 3",
          ordinal = 3,
          slug = "boss3",
          wow_encounter_id = 2565,
        },
        {
          name = "Boss 4",
          ordinal = 4,
          slug = "boss4",
          wow_encounter_id = 2566,
        },
      },
      challenge_mode_id = 402,
      levels = {
        [12] = {
          ["fortified-xalataths-guile"] = {
            boss_splits_ms = { 280000, 740000, 1200000, 1742000 },
            clear_time_ms = 1742000,
            sample_size = 3,
          },
        },
      },
      num_bosses = 4,
      short_name = "AA",
      timer_ms = 1800999,
    },
  },
}
